/* Generated By:JavaCC: Do not edit this line. SSMathParserConstants.java */
package com.babai.ssplot.math.system.parser.internal;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SSMathParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER = 4;
  /** RegularExpression Id. */
  int DIGIT = 5;
  /** RegularExpression Id. */
  int LETTER = 6;
  /** RegularExpression Id. */
  int FN = 7;
  /** RegularExpression Id. */
  int PLUS = 8;
  /** RegularExpression Id. */
  int MINUS = 9;
  /** RegularExpression Id. */
  int TIMES = 10;
  /** RegularExpression Id. */
  int DIV = 11;
  /** RegularExpression Id. */
  int POW = 12;
  /** RegularExpression Id. */
  int BL = 13;
  /** RegularExpression Id. */
  int BR = 14;
  /** RegularExpression Id. */
  int EOL = 15;
  /** RegularExpression Id. */
  int EXIT = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<token of kind 3>",
    "<NUMBER>",
    "<DIGIT>",
    "<LETTER>",
    "<FN>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "<POW>",
    "\"(\"",
    "\")\"",
    "<EOL>",
    "<EXIT>",
  };

}
